// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto

package com.lhldyf.gallery.proto;

public final class Test {
  private Test() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code MovieType}
   */
  public enum MovieType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>CHILDREN = 1;</code>
     */
    CHILDREN(1),
    /**
     * <code>ADULT = 2;</code>
     */
    ADULT(2),
    /**
     * <code>NORMAL = 3;</code>
     */
    NORMAL(3),
    /**
     * <code>OHTER = 4;</code>
     */
    OHTER(4),
    ;

    /**
     * <code>CHILDREN = 1;</code>
     */
    public static final int CHILDREN_VALUE = 1;
    /**
     * <code>ADULT = 2;</code>
     */
    public static final int ADULT_VALUE = 2;
    /**
     * <code>NORMAL = 3;</code>
     */
    public static final int NORMAL_VALUE = 3;
    /**
     * <code>OHTER = 4;</code>
     */
    public static final int OHTER_VALUE = 4;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static MovieType valueOf(int value) {
      return forNumber(value);
    }

    public static MovieType forNumber(int value) {
      switch (value) {
        case 1: return CHILDREN;
        case 2: return ADULT;
        case 3: return NORMAL;
        case 4: return OHTER;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<MovieType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        MovieType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MovieType>() {
            public MovieType findValueByNumber(int number) {
              return MovieType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.lhldyf.gallery.proto.Test.getDescriptor().getEnumTypes().get(0);
    }

    private static final MovieType[] VALUES = values();

    public static MovieType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private MovieType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:MovieType)
  }

  /**
   * Protobuf enum {@code Gender}
   */
  public enum Gender
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>MAN = 1;</code>
     */
    MAN(1),
    /**
     * <code>WOMAN = 2;</code>
     */
    WOMAN(2),
    /**
     * <code>OTHER = 3;</code>
     */
    OTHER(3),
    ;

    /**
     * <code>MAN = 1;</code>
     */
    public static final int MAN_VALUE = 1;
    /**
     * <code>WOMAN = 2;</code>
     */
    public static final int WOMAN_VALUE = 2;
    /**
     * <code>OTHER = 3;</code>
     */
    public static final int OTHER_VALUE = 3;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Gender valueOf(int value) {
      return forNumber(value);
    }

    public static Gender forNumber(int value) {
      switch (value) {
        case 1: return MAN;
        case 2: return WOMAN;
        case 3: return OTHER;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Gender>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Gender> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Gender>() {
            public Gender findValueByNumber(int number) {
              return Gender.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.lhldyf.gallery.proto.Test.getDescriptor().getEnumTypes().get(1);
    }

    private static final Gender[] VALUES = values();

    public static Gender valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Gender(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:Gender)
  }

  public interface MovieOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Movie)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string name = 1;</code>
     */
    boolean hasName();
    /**
     * <code>required string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>required string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>required .MovieType type = 2;</code>
     */
    boolean hasType();
    /**
     * <code>required .MovieType type = 2;</code>
     */
    com.lhldyf.gallery.proto.Test.MovieType getType();

    /**
     * <code>optional int32 releaseTimeStamp = 3;</code>
     */
    boolean hasReleaseTimeStamp();
    /**
     * <code>optional int32 releaseTimeStamp = 3;</code>
     */
    int getReleaseTimeStamp();

    /**
     * <code>optional string description = 4;</code>
     */
    boolean hasDescription();
    /**
     * <code>optional string description = 4;</code>
     */
    java.lang.String getDescription();
    /**
     * <code>optional string description = 4;</code>
     */
    com.google.protobuf.ByteString
        getDescriptionBytes();
  }
  /**
   * Protobuf type {@code Movie}
   */
  public  static final class Movie extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Movie)
      MovieOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Movie.newBuilder() to construct.
    private Movie(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Movie() {
      name_ = "";
      type_ = 1;
      releaseTimeStamp_ = 0;
      description_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Movie(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              name_ = bs;
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
                @SuppressWarnings("deprecation")
              com.lhldyf.gallery.proto.Test.MovieType value = com.lhldyf.gallery.proto.Test.MovieType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                type_ = rawValue;
              }
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              releaseTimeStamp_ = input.readInt32();
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              description_ = bs;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.lhldyf.gallery.proto.Test.internal_static_Movie_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.lhldyf.gallery.proto.Test.internal_static_Movie_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.lhldyf.gallery.proto.Test.Movie.class, com.lhldyf.gallery.proto.Test.Movie.Builder.class);
    }

    private int bitField0_;
    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>required string name = 1;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPE_FIELD_NUMBER = 2;
    private int type_;
    /**
     * <code>required .MovieType type = 2;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .MovieType type = 2;</code>
     */
    public com.lhldyf.gallery.proto.Test.MovieType getType() {
      @SuppressWarnings("deprecation")
      com.lhldyf.gallery.proto.Test.MovieType result = com.lhldyf.gallery.proto.Test.MovieType.valueOf(type_);
      return result == null ? com.lhldyf.gallery.proto.Test.MovieType.CHILDREN : result;
    }

    public static final int RELEASETIMESTAMP_FIELD_NUMBER = 3;
    private int releaseTimeStamp_;
    /**
     * <code>optional int32 releaseTimeStamp = 3;</code>
     */
    public boolean hasReleaseTimeStamp() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 releaseTimeStamp = 3;</code>
     */
    public int getReleaseTimeStamp() {
      return releaseTimeStamp_;
    }

    public static final int DESCRIPTION_FIELD_NUMBER = 4;
    private volatile java.lang.Object description_;
    /**
     * <code>optional string description = 4;</code>
     */
    public boolean hasDescription() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string description = 4;</code>
     */
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          description_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string description = 4;</code>
     */
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, type_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, releaseTimeStamp_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, description_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, type_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, releaseTimeStamp_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, description_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.lhldyf.gallery.proto.Test.Movie)) {
        return super.equals(obj);
      }
      com.lhldyf.gallery.proto.Test.Movie other = (com.lhldyf.gallery.proto.Test.Movie) obj;

      boolean result = true;
      result = result && (hasName() == other.hasName());
      if (hasName()) {
        result = result && getName()
            .equals(other.getName());
      }
      result = result && (hasType() == other.hasType());
      if (hasType()) {
        result = result && type_ == other.type_;
      }
      result = result && (hasReleaseTimeStamp() == other.hasReleaseTimeStamp());
      if (hasReleaseTimeStamp()) {
        result = result && (getReleaseTimeStamp()
            == other.getReleaseTimeStamp());
      }
      result = result && (hasDescription() == other.hasDescription());
      if (hasDescription()) {
        result = result && getDescription()
            .equals(other.getDescription());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasName()) {
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
      }
      if (hasType()) {
        hash = (37 * hash) + TYPE_FIELD_NUMBER;
        hash = (53 * hash) + type_;
      }
      if (hasReleaseTimeStamp()) {
        hash = (37 * hash) + RELEASETIMESTAMP_FIELD_NUMBER;
        hash = (53 * hash) + getReleaseTimeStamp();
      }
      if (hasDescription()) {
        hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
        hash = (53 * hash) + getDescription().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.lhldyf.gallery.proto.Test.Movie parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lhldyf.gallery.proto.Test.Movie parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lhldyf.gallery.proto.Test.Movie parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lhldyf.gallery.proto.Test.Movie parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lhldyf.gallery.proto.Test.Movie parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lhldyf.gallery.proto.Test.Movie parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lhldyf.gallery.proto.Test.Movie parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.lhldyf.gallery.proto.Test.Movie parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.lhldyf.gallery.proto.Test.Movie parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.lhldyf.gallery.proto.Test.Movie parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.lhldyf.gallery.proto.Test.Movie parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.lhldyf.gallery.proto.Test.Movie parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.lhldyf.gallery.proto.Test.Movie prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Movie}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Movie)
        com.lhldyf.gallery.proto.Test.MovieOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.lhldyf.gallery.proto.Test.internal_static_Movie_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.lhldyf.gallery.proto.Test.internal_static_Movie_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.lhldyf.gallery.proto.Test.Movie.class, com.lhldyf.gallery.proto.Test.Movie.Builder.class);
      }

      // Construct using com.lhldyf.gallery.proto.Test.Movie.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = 1;
        bitField0_ = (bitField0_ & ~0x00000002);
        releaseTimeStamp_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        description_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.lhldyf.gallery.proto.Test.internal_static_Movie_descriptor;
      }

      @java.lang.Override
      public com.lhldyf.gallery.proto.Test.Movie getDefaultInstanceForType() {
        return com.lhldyf.gallery.proto.Test.Movie.getDefaultInstance();
      }

      @java.lang.Override
      public com.lhldyf.gallery.proto.Test.Movie build() {
        com.lhldyf.gallery.proto.Test.Movie result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.lhldyf.gallery.proto.Test.Movie buildPartial() {
        com.lhldyf.gallery.proto.Test.Movie result = new com.lhldyf.gallery.proto.Test.Movie(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.releaseTimeStamp_ = releaseTimeStamp_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.description_ = description_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.lhldyf.gallery.proto.Test.Movie) {
          return mergeFrom((com.lhldyf.gallery.proto.Test.Movie)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.lhldyf.gallery.proto.Test.Movie other) {
        if (other == com.lhldyf.gallery.proto.Test.Movie.getDefaultInstance()) return this;
        if (other.hasName()) {
          bitField0_ |= 0x00000001;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasReleaseTimeStamp()) {
          setReleaseTimeStamp(other.getReleaseTimeStamp());
        }
        if (other.hasDescription()) {
          bitField0_ |= 0x00000008;
          description_ = other.description_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasName()) {
          return false;
        }
        if (!hasType()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.lhldyf.gallery.proto.Test.Movie parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.lhldyf.gallery.proto.Test.Movie) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object name_ = "";
      /**
       * <code>required string name = 1;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }

      private int type_ = 1;
      /**
       * <code>required .MovieType type = 2;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .MovieType type = 2;</code>
       */
      public com.lhldyf.gallery.proto.Test.MovieType getType() {
        @SuppressWarnings("deprecation")
        com.lhldyf.gallery.proto.Test.MovieType result = com.lhldyf.gallery.proto.Test.MovieType.valueOf(type_);
        return result == null ? com.lhldyf.gallery.proto.Test.MovieType.CHILDREN : result;
      }
      /**
       * <code>required .MovieType type = 2;</code>
       */
      public Builder setType(com.lhldyf.gallery.proto.Test.MovieType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>required .MovieType type = 2;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        type_ = 1;
        onChanged();
        return this;
      }

      private int releaseTimeStamp_ ;
      /**
       * <code>optional int32 releaseTimeStamp = 3;</code>
       */
      public boolean hasReleaseTimeStamp() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 releaseTimeStamp = 3;</code>
       */
      public int getReleaseTimeStamp() {
        return releaseTimeStamp_;
      }
      /**
       * <code>optional int32 releaseTimeStamp = 3;</code>
       */
      public Builder setReleaseTimeStamp(int value) {
        bitField0_ |= 0x00000004;
        releaseTimeStamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 releaseTimeStamp = 3;</code>
       */
      public Builder clearReleaseTimeStamp() {
        bitField0_ = (bitField0_ & ~0x00000004);
        releaseTimeStamp_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object description_ = "";
      /**
       * <code>optional string description = 4;</code>
       */
      public boolean hasDescription() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string description = 4;</code>
       */
      public java.lang.String getDescription() {
        java.lang.Object ref = description_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            description_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string description = 4;</code>
       */
      public com.google.protobuf.ByteString
          getDescriptionBytes() {
        java.lang.Object ref = description_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          description_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string description = 4;</code>
       */
      public Builder setDescription(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        description_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string description = 4;</code>
       */
      public Builder clearDescription() {
        bitField0_ = (bitField0_ & ~0x00000008);
        description_ = getDefaultInstance().getDescription();
        onChanged();
        return this;
      }
      /**
       * <code>optional string description = 4;</code>
       */
      public Builder setDescriptionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        description_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Movie)
    }

    // @@protoc_insertion_point(class_scope:Movie)
    private static final com.lhldyf.gallery.proto.Test.Movie DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.lhldyf.gallery.proto.Test.Movie();
    }

    public static com.lhldyf.gallery.proto.Test.Movie getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Movie>
        PARSER = new com.google.protobuf.AbstractParser<Movie>() {
      @java.lang.Override
      public Movie parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Movie(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Movie> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Movie> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.lhldyf.gallery.proto.Test.Movie getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CustomerOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Customer)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string name = 1;</code>
     */
    boolean hasName();
    /**
     * <code>required string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>required string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>optional .Gender gender = 2;</code>
     */
    boolean hasGender();
    /**
     * <code>optional .Gender gender = 2;</code>
     */
    com.lhldyf.gallery.proto.Test.Gender getGender();

    /**
     * <code>optional int32 birthdayTimeStamp = 3;</code>
     */
    boolean hasBirthdayTimeStamp();
    /**
     * <code>optional int32 birthdayTimeStamp = 3;</code>
     */
    int getBirthdayTimeStamp();
  }
  /**
   * Protobuf type {@code Customer}
   */
  public  static final class Customer extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Customer)
      CustomerOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Customer.newBuilder() to construct.
    private Customer(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Customer() {
      name_ = "";
      gender_ = 1;
      birthdayTimeStamp_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Customer(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              name_ = bs;
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
                @SuppressWarnings("deprecation")
              com.lhldyf.gallery.proto.Test.Gender value = com.lhldyf.gallery.proto.Test.Gender.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                gender_ = rawValue;
              }
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              birthdayTimeStamp_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.lhldyf.gallery.proto.Test.internal_static_Customer_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.lhldyf.gallery.proto.Test.internal_static_Customer_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.lhldyf.gallery.proto.Test.Customer.class, com.lhldyf.gallery.proto.Test.Customer.Builder.class);
    }

    private int bitField0_;
    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>required string name = 1;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int GENDER_FIELD_NUMBER = 2;
    private int gender_;
    /**
     * <code>optional .Gender gender = 2;</code>
     */
    public boolean hasGender() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .Gender gender = 2;</code>
     */
    public com.lhldyf.gallery.proto.Test.Gender getGender() {
      @SuppressWarnings("deprecation")
      com.lhldyf.gallery.proto.Test.Gender result = com.lhldyf.gallery.proto.Test.Gender.valueOf(gender_);
      return result == null ? com.lhldyf.gallery.proto.Test.Gender.MAN : result;
    }

    public static final int BIRTHDAYTIMESTAMP_FIELD_NUMBER = 3;
    private int birthdayTimeStamp_;
    /**
     * <code>optional int32 birthdayTimeStamp = 3;</code>
     */
    public boolean hasBirthdayTimeStamp() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 birthdayTimeStamp = 3;</code>
     */
    public int getBirthdayTimeStamp() {
      return birthdayTimeStamp_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, gender_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, birthdayTimeStamp_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, gender_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, birthdayTimeStamp_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.lhldyf.gallery.proto.Test.Customer)) {
        return super.equals(obj);
      }
      com.lhldyf.gallery.proto.Test.Customer other = (com.lhldyf.gallery.proto.Test.Customer) obj;

      boolean result = true;
      result = result && (hasName() == other.hasName());
      if (hasName()) {
        result = result && getName()
            .equals(other.getName());
      }
      result = result && (hasGender() == other.hasGender());
      if (hasGender()) {
        result = result && gender_ == other.gender_;
      }
      result = result && (hasBirthdayTimeStamp() == other.hasBirthdayTimeStamp());
      if (hasBirthdayTimeStamp()) {
        result = result && (getBirthdayTimeStamp()
            == other.getBirthdayTimeStamp());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasName()) {
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
      }
      if (hasGender()) {
        hash = (37 * hash) + GENDER_FIELD_NUMBER;
        hash = (53 * hash) + gender_;
      }
      if (hasBirthdayTimeStamp()) {
        hash = (37 * hash) + BIRTHDAYTIMESTAMP_FIELD_NUMBER;
        hash = (53 * hash) + getBirthdayTimeStamp();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.lhldyf.gallery.proto.Test.Customer parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lhldyf.gallery.proto.Test.Customer parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lhldyf.gallery.proto.Test.Customer parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lhldyf.gallery.proto.Test.Customer parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lhldyf.gallery.proto.Test.Customer parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lhldyf.gallery.proto.Test.Customer parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lhldyf.gallery.proto.Test.Customer parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.lhldyf.gallery.proto.Test.Customer parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.lhldyf.gallery.proto.Test.Customer parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.lhldyf.gallery.proto.Test.Customer parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.lhldyf.gallery.proto.Test.Customer parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.lhldyf.gallery.proto.Test.Customer parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.lhldyf.gallery.proto.Test.Customer prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Customer}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Customer)
        com.lhldyf.gallery.proto.Test.CustomerOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.lhldyf.gallery.proto.Test.internal_static_Customer_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.lhldyf.gallery.proto.Test.internal_static_Customer_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.lhldyf.gallery.proto.Test.Customer.class, com.lhldyf.gallery.proto.Test.Customer.Builder.class);
      }

      // Construct using com.lhldyf.gallery.proto.Test.Customer.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        gender_ = 1;
        bitField0_ = (bitField0_ & ~0x00000002);
        birthdayTimeStamp_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.lhldyf.gallery.proto.Test.internal_static_Customer_descriptor;
      }

      @java.lang.Override
      public com.lhldyf.gallery.proto.Test.Customer getDefaultInstanceForType() {
        return com.lhldyf.gallery.proto.Test.Customer.getDefaultInstance();
      }

      @java.lang.Override
      public com.lhldyf.gallery.proto.Test.Customer build() {
        com.lhldyf.gallery.proto.Test.Customer result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.lhldyf.gallery.proto.Test.Customer buildPartial() {
        com.lhldyf.gallery.proto.Test.Customer result = new com.lhldyf.gallery.proto.Test.Customer(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.gender_ = gender_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.birthdayTimeStamp_ = birthdayTimeStamp_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.lhldyf.gallery.proto.Test.Customer) {
          return mergeFrom((com.lhldyf.gallery.proto.Test.Customer)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.lhldyf.gallery.proto.Test.Customer other) {
        if (other == com.lhldyf.gallery.proto.Test.Customer.getDefaultInstance()) return this;
        if (other.hasName()) {
          bitField0_ |= 0x00000001;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasGender()) {
          setGender(other.getGender());
        }
        if (other.hasBirthdayTimeStamp()) {
          setBirthdayTimeStamp(other.getBirthdayTimeStamp());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasName()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.lhldyf.gallery.proto.Test.Customer parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.lhldyf.gallery.proto.Test.Customer) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object name_ = "";
      /**
       * <code>required string name = 1;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }

      private int gender_ = 1;
      /**
       * <code>optional .Gender gender = 2;</code>
       */
      public boolean hasGender() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .Gender gender = 2;</code>
       */
      public com.lhldyf.gallery.proto.Test.Gender getGender() {
        @SuppressWarnings("deprecation")
        com.lhldyf.gallery.proto.Test.Gender result = com.lhldyf.gallery.proto.Test.Gender.valueOf(gender_);
        return result == null ? com.lhldyf.gallery.proto.Test.Gender.MAN : result;
      }
      /**
       * <code>optional .Gender gender = 2;</code>
       */
      public Builder setGender(com.lhldyf.gallery.proto.Test.Gender value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        gender_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .Gender gender = 2;</code>
       */
      public Builder clearGender() {
        bitField0_ = (bitField0_ & ~0x00000002);
        gender_ = 1;
        onChanged();
        return this;
      }

      private int birthdayTimeStamp_ ;
      /**
       * <code>optional int32 birthdayTimeStamp = 3;</code>
       */
      public boolean hasBirthdayTimeStamp() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 birthdayTimeStamp = 3;</code>
       */
      public int getBirthdayTimeStamp() {
        return birthdayTimeStamp_;
      }
      /**
       * <code>optional int32 birthdayTimeStamp = 3;</code>
       */
      public Builder setBirthdayTimeStamp(int value) {
        bitField0_ |= 0x00000004;
        birthdayTimeStamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 birthdayTimeStamp = 3;</code>
       */
      public Builder clearBirthdayTimeStamp() {
        bitField0_ = (bitField0_ & ~0x00000004);
        birthdayTimeStamp_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Customer)
    }

    // @@protoc_insertion_point(class_scope:Customer)
    private static final com.lhldyf.gallery.proto.Test.Customer DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.lhldyf.gallery.proto.Test.Customer();
    }

    public static com.lhldyf.gallery.proto.Test.Customer getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Customer>
        PARSER = new com.google.protobuf.AbstractParser<Customer>() {
      @java.lang.Override
      public Customer parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Customer(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Customer> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Customer> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.lhldyf.gallery.proto.Test.Customer getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TicketOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Ticket)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required int32 id = 1;</code>
     */
    int getId();

    /**
     * <code>required .Movie movie = 2;</code>
     */
    boolean hasMovie();
    /**
     * <code>required .Movie movie = 2;</code>
     */
    com.lhldyf.gallery.proto.Test.Movie getMovie();
    /**
     * <code>required .Movie movie = 2;</code>
     */
    com.lhldyf.gallery.proto.Test.MovieOrBuilder getMovieOrBuilder();

    /**
     * <code>required .Customer customer = 3;</code>
     */
    boolean hasCustomer();
    /**
     * <code>required .Customer customer = 3;</code>
     */
    com.lhldyf.gallery.proto.Test.Customer getCustomer();
    /**
     * <code>required .Customer customer = 3;</code>
     */
    com.lhldyf.gallery.proto.Test.CustomerOrBuilder getCustomerOrBuilder();
  }
  /**
   * Protobuf type {@code Ticket}
   */
  public  static final class Ticket extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Ticket)
      TicketOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Ticket.newBuilder() to construct.
    private Ticket(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Ticket() {
      id_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Ticket(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt32();
              break;
            }
            case 18: {
              com.lhldyf.gallery.proto.Test.Movie.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = movie_.toBuilder();
              }
              movie_ = input.readMessage(com.lhldyf.gallery.proto.Test.Movie.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(movie_);
                movie_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
            case 26: {
              com.lhldyf.gallery.proto.Test.Customer.Builder subBuilder = null;
              if (((bitField0_ & 0x00000004) == 0x00000004)) {
                subBuilder = customer_.toBuilder();
              }
              customer_ = input.readMessage(com.lhldyf.gallery.proto.Test.Customer.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(customer_);
                customer_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000004;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.lhldyf.gallery.proto.Test.internal_static_Ticket_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.lhldyf.gallery.proto.Test.internal_static_Ticket_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.lhldyf.gallery.proto.Test.Ticket.class, com.lhldyf.gallery.proto.Test.Ticket.Builder.class);
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>required int32 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int MOVIE_FIELD_NUMBER = 2;
    private com.lhldyf.gallery.proto.Test.Movie movie_;
    /**
     * <code>required .Movie movie = 2;</code>
     */
    public boolean hasMovie() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .Movie movie = 2;</code>
     */
    public com.lhldyf.gallery.proto.Test.Movie getMovie() {
      return movie_ == null ? com.lhldyf.gallery.proto.Test.Movie.getDefaultInstance() : movie_;
    }
    /**
     * <code>required .Movie movie = 2;</code>
     */
    public com.lhldyf.gallery.proto.Test.MovieOrBuilder getMovieOrBuilder() {
      return movie_ == null ? com.lhldyf.gallery.proto.Test.Movie.getDefaultInstance() : movie_;
    }

    public static final int CUSTOMER_FIELD_NUMBER = 3;
    private com.lhldyf.gallery.proto.Test.Customer customer_;
    /**
     * <code>required .Customer customer = 3;</code>
     */
    public boolean hasCustomer() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required .Customer customer = 3;</code>
     */
    public com.lhldyf.gallery.proto.Test.Customer getCustomer() {
      return customer_ == null ? com.lhldyf.gallery.proto.Test.Customer.getDefaultInstance() : customer_;
    }
    /**
     * <code>required .Customer customer = 3;</code>
     */
    public com.lhldyf.gallery.proto.Test.CustomerOrBuilder getCustomerOrBuilder() {
      return customer_ == null ? com.lhldyf.gallery.proto.Test.Customer.getDefaultInstance() : customer_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMovie()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCustomer()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getMovie().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getCustomer().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, getMovie());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(3, getCustomer());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getMovie());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getCustomer());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.lhldyf.gallery.proto.Test.Ticket)) {
        return super.equals(obj);
      }
      com.lhldyf.gallery.proto.Test.Ticket other = (com.lhldyf.gallery.proto.Test.Ticket) obj;

      boolean result = true;
      result = result && (hasId() == other.hasId());
      if (hasId()) {
        result = result && (getId()
            == other.getId());
      }
      result = result && (hasMovie() == other.hasMovie());
      if (hasMovie()) {
        result = result && getMovie()
            .equals(other.getMovie());
      }
      result = result && (hasCustomer() == other.hasCustomer());
      if (hasCustomer()) {
        result = result && getCustomer()
            .equals(other.getCustomer());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasId()) {
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + getId();
      }
      if (hasMovie()) {
        hash = (37 * hash) + MOVIE_FIELD_NUMBER;
        hash = (53 * hash) + getMovie().hashCode();
      }
      if (hasCustomer()) {
        hash = (37 * hash) + CUSTOMER_FIELD_NUMBER;
        hash = (53 * hash) + getCustomer().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.lhldyf.gallery.proto.Test.Ticket parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lhldyf.gallery.proto.Test.Ticket parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lhldyf.gallery.proto.Test.Ticket parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lhldyf.gallery.proto.Test.Ticket parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lhldyf.gallery.proto.Test.Ticket parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lhldyf.gallery.proto.Test.Ticket parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lhldyf.gallery.proto.Test.Ticket parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.lhldyf.gallery.proto.Test.Ticket parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.lhldyf.gallery.proto.Test.Ticket parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.lhldyf.gallery.proto.Test.Ticket parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.lhldyf.gallery.proto.Test.Ticket parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.lhldyf.gallery.proto.Test.Ticket parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.lhldyf.gallery.proto.Test.Ticket prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Ticket}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Ticket)
        com.lhldyf.gallery.proto.Test.TicketOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.lhldyf.gallery.proto.Test.internal_static_Ticket_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.lhldyf.gallery.proto.Test.internal_static_Ticket_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.lhldyf.gallery.proto.Test.Ticket.class, com.lhldyf.gallery.proto.Test.Ticket.Builder.class);
      }

      // Construct using com.lhldyf.gallery.proto.Test.Ticket.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getMovieFieldBuilder();
          getCustomerFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (movieBuilder_ == null) {
          movie_ = null;
        } else {
          movieBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        if (customerBuilder_ == null) {
          customer_ = null;
        } else {
          customerBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.lhldyf.gallery.proto.Test.internal_static_Ticket_descriptor;
      }

      @java.lang.Override
      public com.lhldyf.gallery.proto.Test.Ticket getDefaultInstanceForType() {
        return com.lhldyf.gallery.proto.Test.Ticket.getDefaultInstance();
      }

      @java.lang.Override
      public com.lhldyf.gallery.proto.Test.Ticket build() {
        com.lhldyf.gallery.proto.Test.Ticket result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.lhldyf.gallery.proto.Test.Ticket buildPartial() {
        com.lhldyf.gallery.proto.Test.Ticket result = new com.lhldyf.gallery.proto.Test.Ticket(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (movieBuilder_ == null) {
          result.movie_ = movie_;
        } else {
          result.movie_ = movieBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (customerBuilder_ == null) {
          result.customer_ = customer_;
        } else {
          result.customer_ = customerBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.lhldyf.gallery.proto.Test.Ticket) {
          return mergeFrom((com.lhldyf.gallery.proto.Test.Ticket)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.lhldyf.gallery.proto.Test.Ticket other) {
        if (other == com.lhldyf.gallery.proto.Test.Ticket.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasMovie()) {
          mergeMovie(other.getMovie());
        }
        if (other.hasCustomer()) {
          mergeCustomer(other.getCustomer());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasId()) {
          return false;
        }
        if (!hasMovie()) {
          return false;
        }
        if (!hasCustomer()) {
          return false;
        }
        if (!getMovie().isInitialized()) {
          return false;
        }
        if (!getCustomer().isInitialized()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.lhldyf.gallery.proto.Test.Ticket parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.lhldyf.gallery.proto.Test.Ticket) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>required int32 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      private com.lhldyf.gallery.proto.Test.Movie movie_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.lhldyf.gallery.proto.Test.Movie, com.lhldyf.gallery.proto.Test.Movie.Builder, com.lhldyf.gallery.proto.Test.MovieOrBuilder> movieBuilder_;
      /**
       * <code>required .Movie movie = 2;</code>
       */
      public boolean hasMovie() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .Movie movie = 2;</code>
       */
      public com.lhldyf.gallery.proto.Test.Movie getMovie() {
        if (movieBuilder_ == null) {
          return movie_ == null ? com.lhldyf.gallery.proto.Test.Movie.getDefaultInstance() : movie_;
        } else {
          return movieBuilder_.getMessage();
        }
      }
      /**
       * <code>required .Movie movie = 2;</code>
       */
      public Builder setMovie(com.lhldyf.gallery.proto.Test.Movie value) {
        if (movieBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          movie_ = value;
          onChanged();
        } else {
          movieBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .Movie movie = 2;</code>
       */
      public Builder setMovie(
          com.lhldyf.gallery.proto.Test.Movie.Builder builderForValue) {
        if (movieBuilder_ == null) {
          movie_ = builderForValue.build();
          onChanged();
        } else {
          movieBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .Movie movie = 2;</code>
       */
      public Builder mergeMovie(com.lhldyf.gallery.proto.Test.Movie value) {
        if (movieBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              movie_ != null &&
              movie_ != com.lhldyf.gallery.proto.Test.Movie.getDefaultInstance()) {
            movie_ =
              com.lhldyf.gallery.proto.Test.Movie.newBuilder(movie_).mergeFrom(value).buildPartial();
          } else {
            movie_ = value;
          }
          onChanged();
        } else {
          movieBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .Movie movie = 2;</code>
       */
      public Builder clearMovie() {
        if (movieBuilder_ == null) {
          movie_ = null;
          onChanged();
        } else {
          movieBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>required .Movie movie = 2;</code>
       */
      public com.lhldyf.gallery.proto.Test.Movie.Builder getMovieBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getMovieFieldBuilder().getBuilder();
      }
      /**
       * <code>required .Movie movie = 2;</code>
       */
      public com.lhldyf.gallery.proto.Test.MovieOrBuilder getMovieOrBuilder() {
        if (movieBuilder_ != null) {
          return movieBuilder_.getMessageOrBuilder();
        } else {
          return movie_ == null ?
              com.lhldyf.gallery.proto.Test.Movie.getDefaultInstance() : movie_;
        }
      }
      /**
       * <code>required .Movie movie = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.lhldyf.gallery.proto.Test.Movie, com.lhldyf.gallery.proto.Test.Movie.Builder, com.lhldyf.gallery.proto.Test.MovieOrBuilder> 
          getMovieFieldBuilder() {
        if (movieBuilder_ == null) {
          movieBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.lhldyf.gallery.proto.Test.Movie, com.lhldyf.gallery.proto.Test.Movie.Builder, com.lhldyf.gallery.proto.Test.MovieOrBuilder>(
                  getMovie(),
                  getParentForChildren(),
                  isClean());
          movie_ = null;
        }
        return movieBuilder_;
      }

      private com.lhldyf.gallery.proto.Test.Customer customer_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.lhldyf.gallery.proto.Test.Customer, com.lhldyf.gallery.proto.Test.Customer.Builder, com.lhldyf.gallery.proto.Test.CustomerOrBuilder> customerBuilder_;
      /**
       * <code>required .Customer customer = 3;</code>
       */
      public boolean hasCustomer() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required .Customer customer = 3;</code>
       */
      public com.lhldyf.gallery.proto.Test.Customer getCustomer() {
        if (customerBuilder_ == null) {
          return customer_ == null ? com.lhldyf.gallery.proto.Test.Customer.getDefaultInstance() : customer_;
        } else {
          return customerBuilder_.getMessage();
        }
      }
      /**
       * <code>required .Customer customer = 3;</code>
       */
      public Builder setCustomer(com.lhldyf.gallery.proto.Test.Customer value) {
        if (customerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          customer_ = value;
          onChanged();
        } else {
          customerBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>required .Customer customer = 3;</code>
       */
      public Builder setCustomer(
          com.lhldyf.gallery.proto.Test.Customer.Builder builderForValue) {
        if (customerBuilder_ == null) {
          customer_ = builderForValue.build();
          onChanged();
        } else {
          customerBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>required .Customer customer = 3;</code>
       */
      public Builder mergeCustomer(com.lhldyf.gallery.proto.Test.Customer value) {
        if (customerBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              customer_ != null &&
              customer_ != com.lhldyf.gallery.proto.Test.Customer.getDefaultInstance()) {
            customer_ =
              com.lhldyf.gallery.proto.Test.Customer.newBuilder(customer_).mergeFrom(value).buildPartial();
          } else {
            customer_ = value;
          }
          onChanged();
        } else {
          customerBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>required .Customer customer = 3;</code>
       */
      public Builder clearCustomer() {
        if (customerBuilder_ == null) {
          customer_ = null;
          onChanged();
        } else {
          customerBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      /**
       * <code>required .Customer customer = 3;</code>
       */
      public com.lhldyf.gallery.proto.Test.Customer.Builder getCustomerBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getCustomerFieldBuilder().getBuilder();
      }
      /**
       * <code>required .Customer customer = 3;</code>
       */
      public com.lhldyf.gallery.proto.Test.CustomerOrBuilder getCustomerOrBuilder() {
        if (customerBuilder_ != null) {
          return customerBuilder_.getMessageOrBuilder();
        } else {
          return customer_ == null ?
              com.lhldyf.gallery.proto.Test.Customer.getDefaultInstance() : customer_;
        }
      }
      /**
       * <code>required .Customer customer = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.lhldyf.gallery.proto.Test.Customer, com.lhldyf.gallery.proto.Test.Customer.Builder, com.lhldyf.gallery.proto.Test.CustomerOrBuilder> 
          getCustomerFieldBuilder() {
        if (customerBuilder_ == null) {
          customerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.lhldyf.gallery.proto.Test.Customer, com.lhldyf.gallery.proto.Test.Customer.Builder, com.lhldyf.gallery.proto.Test.CustomerOrBuilder>(
                  getCustomer(),
                  getParentForChildren(),
                  isClean());
          customer_ = null;
        }
        return customerBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Ticket)
    }

    // @@protoc_insertion_point(class_scope:Ticket)
    private static final com.lhldyf.gallery.proto.Test.Ticket DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.lhldyf.gallery.proto.Test.Ticket();
    }

    public static com.lhldyf.gallery.proto.Test.Ticket getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Ticket>
        PARSER = new com.google.protobuf.AbstractParser<Ticket>() {
      @java.lang.Override
      public Ticket parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Ticket(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Ticket> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Ticket> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.lhldyf.gallery.proto.Test.Ticket getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Movie_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Movie_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Customer_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Customer_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Ticket_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Ticket_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ntest.proto\"^\n\005Movie\022\014\n\004name\030\001 \002(\t\022\030\n\004t" +
      "ype\030\002 \002(\0162\n.MovieType\022\030\n\020releaseTimeStam" +
      "p\030\003 \001(\005\022\023\n\013description\030\004 \001(\t\"L\n\010Customer" +
      "\022\014\n\004name\030\001 \002(\t\022\027\n\006gender\030\002 \001(\0162\007.Gender\022" +
      "\031\n\021birthdayTimeStamp\030\003 \001(\005\"H\n\006Ticket\022\n\n\002" +
      "id\030\001 \002(\005\022\025\n\005movie\030\002 \002(\0132\006.Movie\022\033\n\010custo" +
      "mer\030\003 \002(\0132\t.Customer*;\n\tMovieType\022\014\n\010CHI" +
      "LDREN\020\001\022\t\n\005ADULT\020\002\022\n\n\006NORMAL\020\003\022\t\n\005OHTER\020" +
      "\004*\'\n\006Gender\022\007\n\003MAN\020\001\022\t\n\005WOMAN\020\002\022\t\n\005OTHER" +
      "\020\003B\032\n\030com.lhldyf.gallery.proto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Movie_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Movie_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Movie_descriptor,
        new java.lang.String[] { "Name", "Type", "ReleaseTimeStamp", "Description", });
    internal_static_Customer_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Customer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Customer_descriptor,
        new java.lang.String[] { "Name", "Gender", "BirthdayTimeStamp", });
    internal_static_Ticket_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Ticket_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Ticket_descriptor,
        new java.lang.String[] { "Id", "Movie", "Customer", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
